# Defines what is allowed

repository:
  naming:
    pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"   # Repository names must contain lowercase letters and digits, optionally contain hyphens and not start/end with a hyphen

